### ISSUE TITLE
Doesn't seem to work in Firefox

### ISSUE THREAD

**Issue by zohf** [terrymun/paver#4] opened 2016-03-14 00:19 UTC
Any thoughts as to why? Not seeing any console errors.

**Comment by terrymun** [comment] 2016-03-14 07:33
That's because at a certain point Firefox started to support DeviceOrientation yet does not feed any gyroscopic data or trigger the deviceorientation event. That'll be corrected in a fix soon.

**Comment by zohf** [comment] 2016-03-15 17:08
@terrymun Thanks Terry! The way it degrades is great, and was perfectly fine. I used Paver here if you'd like to see it in action: http://www.theverge.com/2016/3/14/11179572/first-lady-michelle-obama-vr-interview-social-media-pictures

Thanks again!

**Comment by terrymun** [comment] 2016-03-15 17:36
I'm flattered (and absolutely humbled) of you using the plugin on such an amazing piece on Michele Obama!

That's only going to motivate me even more to attempt to fix it for Firefox users. I kind of have an idea how the fix would be, just need to test it out later today.

**Comment by terrymun** [comment] 2016-03-15 22:36
Hi @zohf, I can confirm that the Firefox issue has been fixed as of v1.3.0 :)

**Closed as completed by terrymun** 2016-03-15 22:36 UTC
Labels: bug

**Comment by zohf** [comment] 2016-03-16 00:38
🔥 thanks @terrymun!
